spring:
  application:
    name: companyapp
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    locations: db/migration/postgres
management:
  endpoints:
    web:
      exposure:
        include: [ 'prometheus' ]
#  metrics: #TODO: incompatible with OTEL collector
#    distribution:
#      percentiles:
#        http.server.requests: 0.5, 0.75, 0.9, 0.95, 0.99
#        company.db: 0.5, 0.75, 0.9, 0.95, 0.99
#      percentiles-histogram:
#        http.server.requests: true
#        company.db: true
