version: '3.9'

services:
  company-app:
    container_name: company-app
    build:
      context: ./company
      dockerfile: docker/Dockerfile
    command: [ "java", "-Xdebug", "-Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "./company-app.jar" ]
    ports:
      - '8080:8080'
      - '5005:5005'
    networks:
      - microservices-demo-network
    depends_on:
      company-app-db:
        condition: service_healthy

  company-app-db:
    container_name: company-db
    image: postgres:15.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=microservicesdemodb
    ports:
      - '5432:5432'
    volumes:
      - microservices-demo-company-db:/var/lib/postgresql/data
    networks:
      - microservices-demo-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 10

  prometheus:
    container_name: company-prometheus
    image: prom/prometheus:v2.48.0
    ports:
      - "9090:9090"
    volumes:
      - microservices-demo-prometheus-db:/prometheus
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - microservices-demo-network

  grafana:
    container_name: company-grafana
    image: grafana/grafana:10.2.2
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - microservices-demo-network

volumes:
  microservices-demo-company-db:
  microservices-demo-prometheus-db:

networks:
  microservices-demo-network:
