# Add each RPi as it gets provisioned.
# ansible_host = IP address (DHCP reservation in Omada)
# inventory hostname (e.g. k8s-rpi-worker-1) = target hostname set by the playbook
# naming convention: k8s-rpi-* (distinguishes these from other RPis on the same Omada network)

[k8s_master]
k8s-rpi-master ansible_host=192.168.10.1

[k8s_workers]
k8s-rpi-worker-1 ansible_host=192.168.10.10
k8s-rpi-worker-2 ansible_host=192.168.10.11
# k8s-rpi-worker-3 ansible_host=192.168.10.12
# k8s-rpi-worker-4 ansible_host=192.168.10.13

[k8s_database]
k8s-rpi-db-1 ansible_host=192.168.10.50
k8s-rpi-db-2 ansible_host=192.168.10.51

[k8s_observability]
k8s-rpi-observability-1 ansible_host=192.168.10.90

[k8s_all:children]
k8s_master
k8s_database
k8s_observability
k8s_workers

[k8s_all:vars]
ansible_user=aarczynski
