spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    locations: db/migration/postgres
management:
  observations:
    annotations:
      enabled: true
  endpoints:
    web:
      exposure:
        include: [ 'health', 'prometheus' ]
