spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/microservicesdemodb
    username: postgres
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true