spring:
  datasource:
    url: jdbc:postgresql://company-app-db:5432/microservicesdemodb
    username: postgres
    password: password
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
