#scrape_configs:
#  - job_name: 'company-app'
#    metrics_path: '/actuator/prometheus'
#    scrape_interval: 1s
#    scrape_timeout: 1s
#    static_configs:
#      - targets: ['company-app:8080']
#  - job_name: 'otel_collector'
#    metrics_path: '/metrics'
#    honor_timestamps: true
#    scrape_interval: 1s
#    scrape_timeout: 1s
#    static_configs:
#      - targets:
#          - otel-collector:8889
