spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/app-company-db
    username: postgres
    password: password
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
