scrape_configs:
  - job_name: 'CompanyAppMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    scrape_timeout: 15s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'Company Application'
