{
 "title": "HTTP Monitoring",
 "tags": [
  "microservices",
  "http"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{job=~\"app-.*\"}, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (http_route) (rate(http_server_request_duration_seconds_count{job=\"$service\", http_route=~\"/api.*\"}[5s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (http_response_status_code, http_request_method, http_route) (rate(http_server_request_duration_seconds_count{job=\"$service\", http_route=~\"/api.*\", http_response_status_code!~\"2..\"}[5s]))",
     "legendFormat": "{{http_response_status_code}} - ({{http_request_method}}) {{http_route}}"
    }
   ]
  },
  {
   "title": "Web Response Times [ms]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "1000 * histogram_quantile(0.50, sum by (le, http_route) (rate(http_server_request_duration_seconds_bucket{job=\"$service\", http_route=~\"/api.*\"}[5s])))",
     "legendFormat": "{{http_route}} 50th percentile (median)"
    },
    {
     "expr": "1000 * histogram_quantile(0.75, sum by (le, http_route) (rate(http_server_request_duration_seconds_bucket{job=\"$service\", http_route=~\"/api.*\"}[5s])))",
     "legendFormat": "{{http_route}} 75th percentile"
    },
    {
     "expr": "1000 * histogram_quantile(0.90, sum by (le, http_route) (rate(http_server_request_duration_seconds_bucket{job=\"$service\", http_route=~\"/api.*\"}[5s])))",
     "legendFormat": "{{http_route}} 90th percentile"
    },
    {
     "expr": "1000 * histogram_quantile(0.95, sum by (le, http_route) (rate(http_server_request_duration_seconds_bucket{job=\"$service\", http_route=~\"/api.*\"}[5s])))",
     "legendFormat": "{{http_route}} 95th percentile"
    },
    {
     "expr": "1000 * histogram_quantile(0.99, sum by (le, http_route) (rate(http_server_request_duration_seconds_bucket{job=\"$service\", http_route=~\"/api.*\"}[5s])))",
     "legendFormat": "{{http_route}} 99th percentile"
    },
    {
     "expr": "1000 * (sum by (http_route) (rate(http_server_request_duration_seconds_sum{job=\"$service\", http_route=~\"/api.*\"}[5s]))) / (sum by (http_route) (rate(http_server_request_duration_seconds_count{job=\"$service\", http_route=~\"/api.*\"}[5s])))",
     "legendFormat": "{{http_route}} average"
    }
   ]
  },
  {
   "title": "DB Response Times [ms]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "1000 * histogram_quantile(0.50, sum by (le) (\n  rate(db_client_operation_duration_seconds_bucket{job=\"$service\", db_query_summary=~\"(?i)select .+\"}[5s])\n))",
     "legendFormat": "50th percentile (median)"
    },
    {
     "expr": "1000 * histogram_quantile(0.75, sum by (le) (\n  rate(db_client_operation_duration_seconds_bucket{job=\"$service\", db_query_summary=~\"(?i)select .+\"}[5s])\n))",
     "legendFormat": "75th percentile"
    },
    {
     "expr": "1000 * histogram_quantile(0.90, sum by (le) (\n  rate(db_client_operation_duration_seconds_bucket{job=\"$service\", db_query_summary=~\"(?i)select .+\"}[5s])\n))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "1000 * histogram_quantile(0.95, sum by (le) (\n  rate(db_client_operation_duration_seconds_bucket{job=\"$service\", db_query_summary=~\"(?i)select .+\"}[5s])\n))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "1000 * histogram_quantile(0.99, sum by (le) (\n  rate(db_client_operation_duration_seconds_bucket{job=\"$service\", db_query_summary=~\"(?i)select .+\"}[5s])\n))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "1000 * sum(rate(db_client_operation_duration_seconds_sum{job=\"$service\", db_query_summary=~\"(?i)select .+\"}[5s]))\n/\nsum(rate(db_client_operation_duration_seconds_count{job=\"$service\", db_query_summary=~\"(?i)select .+\"}[5s]))",
     "legendFormat": "average"
    }
   ]
  }
 ]
}