spring:
  jpa:
    open-in-view: false
    database: postgresql
    hibernate:
      ddl-auto: validate
  flyway:
    locations: db/migration/postgres
management:
  endpoints:
    web:
      exposure:
        include: ['prometheus']
  metrics:
    distribution:
      percentiles-histogram[http.server.requests]: true
      percentiles[http.server.requests]: 0.5, 0.75, 0.9, 0.95, 0.99
