spring:
  application:
    name: companyapp
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    locations: db/migration/postgres
management:
  endpoints:
    web:
      exposure:
        include: [ 'prometheus' ]
  metrics:
    distribution:
      percentiles:
        http.server.requests: 0.5, 0.75, 0.9, 0.95, 0.99
        company.db: 0.5, 0.75, 0.9, 0.95, 0.99
      percentiles-histogram:
        http.server.requests: true
        company.db: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://tempo:9411/api/v2/spans
logging:
  pattern:
    correlation: '[${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
