spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demodb
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations: db/migration/postgres