spring:
  jpa:
    open-in-view: false
    database: postgresql
    hibernate:
      ddl-auto: validate
  flyway:
    locations: db/migration/postgres
management:
  endpoints:
    web:
      exposure:
        include: ['prometheus']
